package screens

// IANAZones is the curated list of timezone IDs offered in the Profile
// screen's timezone picker. Go's stdlib has no equivalent to .NET's
// TimeZoneInfo.GetSystemTimeZones(), and shipping the entire tzdata listing
// (~600 entries) would drown the searchable-list widget. This is the
// hand-picked set that covers ≥99 % of real-world BBS users: every IANA
// region's principal cities plus a handful of common fixed-offset aliases.
//
// Sorted alphabetically so the typeahead filter and the linear cursor walk
// produce a predictable order.
var IANAZones = []string{
	"UTC",
	"Africa/Cairo",
	"Africa/Casablanca",
	"Africa/Johannesburg",
	"Africa/Lagos",
	"Africa/Nairobi",
	"America/Anchorage",
	"America/Argentina/Buenos_Aires",
	"America/Bogota",
	"America/Chicago",
	"America/Denver",
	"America/Edmonton",
	"America/Halifax",
	"America/Havana",
	"America/Indiana/Indianapolis",
	"America/Lima",
	"America/Los_Angeles",
	"America/Mexico_City",
	"America/Montevideo",
	"America/New_York",
	"America/Phoenix",
	"America/Regina",
	"America/Santiago",
	"America/Sao_Paulo",
	"America/St_Johns",
	"America/Toronto",
	"America/Vancouver",
	"America/Winnipeg",
	"Antarctica/McMurdo",
	"Asia/Almaty",
	"Asia/Baghdad",
	"Asia/Bangkok",
	"Asia/Beirut",
	"Asia/Calcutta",
	"Asia/Dhaka",
	"Asia/Dubai",
	"Asia/Hong_Kong",
	"Asia/Irkutsk",
	"Asia/Jakarta",
	"Asia/Jerusalem",
	"Asia/Kabul",
	"Asia/Karachi",
	"Asia/Kolkata",
	"Asia/Krasnoyarsk",
	"Asia/Kuala_Lumpur",
	"Asia/Kuwait",
	"Asia/Manila",
	"Asia/Riyadh",
	"Asia/Seoul",
	"Asia/Shanghai",
	"Asia/Singapore",
	"Asia/Taipei",
	"Asia/Tashkent",
	"Asia/Tehran",
	"Asia/Tokyo",
	"Asia/Ulaanbaatar",
	"Asia/Vladivostok",
	"Asia/Yakutsk",
	"Asia/Yekaterinburg",
	"Atlantic/Azores",
	"Atlantic/Reykjavik",
	"Australia/Adelaide",
	"Australia/Brisbane",
	"Australia/Darwin",
	"Australia/Hobart",
	"Australia/Melbourne",
	"Australia/Perth",
	"Australia/Sydney",
	"Europe/Amsterdam",
	"Europe/Athens",
	"Europe/Belgrade",
	"Europe/Berlin",
	"Europe/Brussels",
	"Europe/Bucharest",
	"Europe/Budapest",
	"Europe/Copenhagen",
	"Europe/Dublin",
	"Europe/Helsinki",
	"Europe/Istanbul",
	"Europe/Kiev",
	"Europe/Lisbon",
	"Europe/London",
	"Europe/Madrid",
	"Europe/Minsk",
	"Europe/Moscow",
	"Europe/Oslo",
	"Europe/Paris",
	"Europe/Prague",
	"Europe/Riga",
	"Europe/Rome",
	"Europe/Sofia",
	"Europe/Stockholm",
	"Europe/Tallinn",
	"Europe/Vienna",
	"Europe/Vilnius",
	"Europe/Warsaw",
	"Europe/Zurich",
	"Pacific/Auckland",
	"Pacific/Fiji",
	"Pacific/Guam",
	"Pacific/Honolulu",
	"Pacific/Midway",
	"Pacific/Pago_Pago",
	"Pacific/Port_Moresby",
}
