-- Per-user state for the Carbonyl-backed Web screen: a curated bookmark list
-- and an automatic visit history. Distinct lifecycles → distinct tables, no
-- cross-reference. Bookmarks are opinions the user expressed; history is the
-- record of where they went.
--
-- The earlier user_bookmarks table (migration 4, dropped in 7) belonged to the
-- since-removed reader-mode browser. These are not its successor — Carbonyl
-- has no built-in bookmark UI of its own, so the BBS owns this state on the
-- user's behalf.

CREATE TABLE public.web_bookmarks (
    id         bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_web_bookmarks PRIMARY KEY,
    user_id    bigint NOT NULL,
    url        text   NOT NULL,
    title      text   NOT NULL DEFAULT '',
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ix_web_bookmarks_user_id_url ON public.web_bookmarks(user_id, url);
CREATE INDEX        ix_web_bookmarks_user_id_sort ON public.web_bookmarks(user_id, sort_order, created_at DESC);

ALTER TABLE public.web_bookmarks
    ADD CONSTRAINT fk_web_bookmarks_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

CREATE TABLE public.web_history (
    id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_web_history PRIMARY KEY,
    user_id         bigint NOT NULL,
    url             text   NOT NULL,
    last_visited_at timestamp with time zone NOT NULL DEFAULT now(),
    visit_count     integer NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX ix_web_history_user_id_url ON public.web_history(user_id, url);
CREATE INDEX        ix_web_history_user_recent ON public.web_history(user_id, last_visited_at DESC);

ALTER TABLE public.web_history
    ADD CONSTRAINT fk_web_history_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
