-- Initial schema for ssh.night.ms.
--
-- Source: pg_dump --schema-only of a freshly-migrated legacy DB. We deliberately
-- do not translate the 33 source migration files one-by-one; the shape they
-- collectively produce is the contract.
--
-- Differences vs the raw pg_dump output:
--   - The legacy migration history table is omitted (golang-migrate uses its own).
--   - psql-only commands (\restrict, \unrestrict, search_path set_config) stripped.
--   - SET statements relaxed to defaults; the migrator's connection already has
--     sensible session settings.

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;

SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public.audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_audit_log PRIMARY KEY,
    actor_id bigint,
    action character varying(64) NOT NULL,
    target_type character varying(64) NOT NULL,
    target_id bigint,
    details jsonb,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users PRIMARY KEY,
    handle public.citext NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone,
    is_sysop boolean NOT NULL,
    is_banned boolean NOT NULL,
    bio character varying(500),
    location character varying(64),
    real_name character varying(64),
    clock_format integer DEFAULT 0 NOT NULL,
    date_format integer DEFAULT 0 NOT NULL,
    temperature_unit integer DEFAULT 0 NOT NULL,
    time_zone_id character varying(64) DEFAULT 'UTC'::character varying NOT NULL,
    location_canonical character varying(160),
    location_latitude double precision,
    location_longitude double precision,
    location_source integer DEFAULT 0 NOT NULL,
    email public.citext,
    profile_picture_updated_at timestamp with time zone,
    password_algo character varying(64),
    password_hash bytea,
    password_updated_at timestamp with time zone,
    suppress_key_adoption_prompts boolean DEFAULT false NOT NULL,
    require_ssh_key boolean DEFAULT false NOT NULL
);

CREATE TABLE public.channels (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_channels PRIMARY KEY,
    name public.citext NOT NULL,
    topic text,
    is_private boolean NOT NULL,
    created_by_id bigint,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.channel_members (
    channel_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    role character varying(32) NOT NULL,
    CONSTRAINT pk_channel_members PRIMARY KEY (channel_id, user_id)
);

CREATE TABLE public.channel_reads (
    user_id bigint NOT NULL,
    channel_id bigint NOT NULL,
    last_read_message_id bigint NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_channel_reads PRIMARY KEY (user_id, channel_id)
);

CREATE TABLE public.chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_chat_messages PRIMARY KEY,
    channel_id bigint NOT NULL,
    user_id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    edited_at timestamp with time zone,
    is_pinned boolean DEFAULT false NOT NULL,
    parent_message_id bigint,
    body_search tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, body)) STORED
);

CREATE TABLE public.message_reactions (
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    emoji character varying(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_message_reactions PRIMARY KEY (message_id, user_id, emoji)
);

CREATE TABLE public.forums (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_forums PRIMARY KEY,
    name character varying(64) NOT NULL,
    description text,
    sort_order integer NOT NULL
);

CREATE TABLE public.topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_topics PRIMARY KEY,
    forum_id bigint NOT NULL,
    title character varying(120) NOT NULL,
    created_by_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_post_at timestamp with time zone NOT NULL
);

CREATE TABLE public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_posts PRIMARY KEY,
    topic_id bigint NOT NULL,
    parent_post_id bigint,
    body text NOT NULL,
    created_by_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    edited_at timestamp with time zone
);

CREATE TABLE public.post_reads (
    user_id bigint NOT NULL,
    topic_id bigint NOT NULL,
    last_read_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_post_reads PRIMARY KEY (user_id, topic_id)
);

CREATE TABLE public.identity_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_identity_credentials PRIMARY KEY,
    user_id bigint NOT NULL,
    provider character varying(32) NOT NULL,
    subject character varying(255) NOT NULL,
    metadata jsonb,
    label character varying(80),
    created_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone
);

CREATE TABLE public.user_wallets (
    user_id bigint NOT NULL CONSTRAINT pk_user_wallets PRIMARY KEY,
    daily_credits integer NOT NULL,
    daily_credits_refreshed_on date,
    winnings_balance bigint NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_saved_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_user_saved_locations PRIMARY KEY,
    user_id bigint NOT NULL,
    label character varying(64) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    canonical character varying(160),
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_watchlist_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_user_watchlist_items PRIMARY KEY,
    user_id bigint NOT NULL,
    symbol character varying(32) NOT NULL,
    canonical character varying(64) NOT NULL,
    kind integer NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.game_rounds (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_game_rounds PRIMARY KEY,
    user_id bigint NOT NULL,
    game_key character varying(32) NOT NULL,
    bet integer NOT NULL,
    payout integer NOT NULL,
    net integer NOT NULL,
    details jsonb,
    played_at timestamp with time zone NOT NULL,
    hand_id bigint
);

CREATE TABLE public.multiplayer_hands (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_multiplayer_hands PRIMARY KEY,
    game_key character varying(32) NOT NULL,
    table_id bigint NOT NULL,
    hand_no bigint NOT NULL,
    details jsonb NOT NULL,
    settled_at timestamp with time zone NOT NULL
);

-- Indexes

CREATE INDEX ix_audit_log_actor_id ON public.audit_log USING btree (actor_id);
CREATE UNIQUE INDEX ix_users_handle ON public.users USING btree (handle);
CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email);
CREATE UNIQUE INDEX ix_channels_name ON public.channels USING btree (name);
CREATE INDEX ix_channels_created_by_id ON public.channels USING btree (created_by_id);
CREATE INDEX ix_channel_members_user_id ON public.channel_members USING btree (user_id);
CREATE INDEX ix_channel_reads_channel_id ON public.channel_reads USING btree (channel_id);
CREATE INDEX ix_channel_reads_user_id_updated_at ON public.channel_reads USING btree (user_id, updated_at DESC);
CREATE INDEX ix_chat_messages_channel_id_created_at ON public.chat_messages USING btree (channel_id, created_at DESC);
CREATE INDEX ix_chat_messages_parent_message_id ON public.chat_messages USING btree (parent_message_id);
CREATE INDEX ix_chat_messages_user_id ON public.chat_messages USING btree (user_id);
CREATE INDEX ix_chat_messages_body_search ON public.chat_messages USING gin (body_search);
CREATE INDEX ix_message_reactions_message_id ON public.message_reactions USING btree (message_id);
CREATE INDEX ix_message_reactions_user_id ON public.message_reactions USING btree (user_id);
CREATE UNIQUE INDEX ix_forums_name ON public.forums USING btree (name);
CREATE INDEX ix_topics_created_by_id ON public.topics USING btree (created_by_id);
CREATE INDEX ix_topics_forum_id_last_post_at ON public.topics USING btree (forum_id, last_post_at DESC);
CREATE INDEX ix_posts_created_by_id ON public.posts USING btree (created_by_id);
CREATE INDEX ix_posts_parent_post_id ON public.posts USING btree (parent_post_id);
CREATE INDEX ix_posts_topic_id ON public.posts USING btree (topic_id);
CREATE INDEX ix_post_reads_topic_id ON public.post_reads USING btree (topic_id);
CREATE UNIQUE INDEX ix_identity_credentials_provider_subject ON public.identity_credentials USING btree (provider, subject);
CREATE INDEX ix_identity_credentials_user_id ON public.identity_credentials USING btree (user_id);
CREATE UNIQUE INDEX ix_user_saved_locations_user_id_label ON public.user_saved_locations USING btree (user_id, label);
CREATE INDEX ix_user_saved_locations_user_id_sort_order ON public.user_saved_locations USING btree (user_id, sort_order);
CREATE UNIQUE INDEX ix_user_watchlist_items_user_id_canonical ON public.user_watchlist_items USING btree (user_id, canonical);
CREATE INDEX ix_user_watchlist_items_user_id_sort_order ON public.user_watchlist_items USING btree (user_id, sort_order);
CREATE INDEX ix_game_rounds_game_key_net ON public.game_rounds USING btree (game_key, net DESC);
CREATE INDEX ix_game_rounds_game_key_played_at ON public.game_rounds USING btree (game_key, played_at DESC);
CREATE INDEX ix_game_rounds_hand_id ON public.game_rounds USING btree (hand_id);
CREATE INDEX ix_game_rounds_user_id_played_at ON public.game_rounds USING btree (user_id, played_at DESC);
CREATE UNIQUE INDEX ix_multiplayer_hands_game_key_table_id_hand_no ON public.multiplayer_hands USING btree (game_key, table_id, hand_no);

-- Foreign keys

ALTER TABLE public.audit_log
    ADD CONSTRAINT fk_audit_log_users_actor_id FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.channels
    ADD CONSTRAINT fk_channels_users_created_by_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.channel_members
    ADD CONSTRAINT fk_channel_members_channels_channel_id FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE;
ALTER TABLE public.channel_members
    ADD CONSTRAINT fk_channel_members_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.channel_reads
    ADD CONSTRAINT fk_channel_reads_channels_channel_id FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE;
ALTER TABLE public.channel_reads
    ADD CONSTRAINT fk_channel_reads_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.chat_messages
    ADD CONSTRAINT fk_chat_messages_channels_channel_id FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE;
ALTER TABLE public.chat_messages
    ADD CONSTRAINT fk_chat_messages_chat_messages_parent_message_id FOREIGN KEY (parent_message_id) REFERENCES public.chat_messages(id) ON DELETE RESTRICT;
ALTER TABLE public.chat_messages
    ADD CONSTRAINT fk_chat_messages_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.message_reactions
    ADD CONSTRAINT fk_message_reactions_chat_messages_message_id FOREIGN KEY (message_id) REFERENCES public.chat_messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_reactions
    ADD CONSTRAINT fk_message_reactions_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.topics
    ADD CONSTRAINT fk_topics_forums_forum_id FOREIGN KEY (forum_id) REFERENCES public.forums(id) ON DELETE CASCADE;
ALTER TABLE public.topics
    ADD CONSTRAINT fk_topics_users_created_by_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.posts
    ADD CONSTRAINT fk_posts_posts_parent_post_id FOREIGN KEY (parent_post_id) REFERENCES public.posts(id) ON DELETE RESTRICT;
ALTER TABLE public.posts
    ADD CONSTRAINT fk_posts_topics_topic_id FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;
ALTER TABLE public.posts
    ADD CONSTRAINT fk_posts_users_created_by_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.post_reads
    ADD CONSTRAINT fk_post_reads_topics_topic_id FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;
ALTER TABLE public.post_reads
    ADD CONSTRAINT fk_post_reads_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.identity_credentials
    ADD CONSTRAINT fk_identity_credentials_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_wallets
    ADD CONSTRAINT fk_user_wallets_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_saved_locations
    ADD CONSTRAINT fk_user_saved_locations_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_watchlist_items
    ADD CONSTRAINT fk_user_watchlist_items_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_rounds
    ADD CONSTRAINT fk_game_rounds_multiplayer_hands_hand_id FOREIGN KEY (hand_id) REFERENCES public.multiplayer_hands(id) ON DELETE SET NULL;
ALTER TABLE public.game_rounds
    ADD CONSTRAINT fk_game_rounds_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
