-- Recreates user_bookmarks for rollback. Mirrors the schema as it existed at
-- migration 000004 so a downgrade lands a working (but empty) table — data
-- destroyed by the up-migration is not recovered.

CREATE TABLE public.user_bookmarks (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_user_bookmarks PRIMARY KEY,
    user_id bigint NOT NULL,
    url text NOT NULL,
    title character varying(255) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX ix_user_bookmarks_user_id_url ON public.user_bookmarks(user_id, url);
CREATE INDEX        ix_user_bookmarks_user_id_sort ON public.user_bookmarks(user_id, sort_order, created_at DESC);

ALTER TABLE public.user_bookmarks
    ADD CONSTRAINT fk_user_bookmarks_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
