-- Browser screen bookmarks. Per-user list of saved URLs, sorted by a manual
-- sort_order (auto-incremented at insert) with created_at as the tiebreaker.
-- The unique (user_id, url) index lets the AddBookmark upsert refresh a
-- title without growing the table when the user re-bookmarks a page.

CREATE TABLE public.user_bookmarks (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_user_bookmarks PRIMARY KEY,
    user_id bigint NOT NULL,
    url text NOT NULL,
    title character varying(255) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX ix_user_bookmarks_user_id_url ON public.user_bookmarks(user_id, url);
CREATE INDEX        ix_user_bookmarks_user_id_sort ON public.user_bookmarks(user_id, sort_order, created_at DESC);

ALTER TABLE public.user_bookmarks
    ADD CONSTRAINT fk_user_bookmarks_users_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
