-- OneNote integration: thin local cache + mapping over Microsoft Graph
-- (internal/onenote). Graph is the source of truth — these tables never
-- mirror a user's full notebook tree. They exist only to (1) hold per-user
-- prefs (default notebook/section), (2) keep a stable "recent pages" list so
-- the lobby/REST can render without a Graph round-trip, and (3) cache a
-- recently-viewed page's parsed content for a short TTL so a redeploy or a
-- second viewer doesn't force a re-fetch.
--
-- All three are keyed by user_id and cascade-deleted with the user. Graph
-- object IDs (notebook/section/page) are opaque provider strings, stored as
-- plain text — they are NOT our identity_credentials ids.

CREATE TABLE IF NOT EXISTS public.onenote_user_prefs (
    user_id             bigint NOT NULL
        CONSTRAINT pk_onenote_user_prefs PRIMARY KEY
        CONSTRAINT fk_onenote_user_prefs_users
            REFERENCES public.users(id) ON DELETE CASCADE,
    default_notebook_id text,
    default_section_id  text,
    last_synced_at      timestamp with time zone,
    created_at          timestamp with time zone NOT NULL,
    updated_at          timestamp with time zone NOT NULL
);

-- Recent-pages mapping: the user's most-recently-opened OneNote pages. Drives
-- the "jump back in" list without re-listing sections from Graph. UNIQUE on
-- (user_id, page_id) so re-opening a page bumps last_viewed_at instead of
-- inserting a duplicate; the partial-free index supports the ORDER BY scan.
CREATE TABLE IF NOT EXISTS public.onenote_recent_pages (
    id               bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_onenote_recent_pages PRIMARY KEY,
    user_id          bigint NOT NULL
        CONSTRAINT fk_onenote_recent_pages_users
            REFERENCES public.users(id) ON DELETE CASCADE,
    page_id          text NOT NULL,
    section_id       text,
    title            text NOT NULL DEFAULT '',
    web_url          text,
    page_modified_at timestamp with time zone,
    last_viewed_at   timestamp with time zone NOT NULL,
    created_at       timestamp with time zone NOT NULL,
    CONSTRAINT uq_onenote_recent_pages_user_page UNIQUE (user_id, page_id)
);

CREATE INDEX IF NOT EXISTS ix_onenote_recent_pages_user_viewed
    ON public.onenote_recent_pages (user_id, last_viewed_at DESC);

-- Short-TTL content cache for recently-viewed pages. html is the raw
-- includeIDs=true Graph HTML (retained for edit targeting); blocks is the
-- pre-parsed render model ([]Block + []EditableElement) so a cache hit skips
-- both the Graph fetch and the HTML walk. fetched_at drives the soft TTL.
CREATE TABLE IF NOT EXISTS public.onenote_page_cache (
    user_id          bigint NOT NULL
        CONSTRAINT fk_onenote_page_cache_users
            REFERENCES public.users(id) ON DELETE CASCADE,
    page_id          text NOT NULL,
    html             text NOT NULL,
    blocks           jsonb NOT NULL,
    page_modified_at timestamp with time zone,
    fetched_at       timestamp with time zone NOT NULL,
    CONSTRAINT pk_onenote_page_cache PRIMARY KEY (user_id, page_id)
);
