-- Phase B/C of the SSH-hardening workstream. Two tables:
--
--   security_events  — append-only audit log of authn / netlimit / handshake
--                      activity. Read by the sysop UI events feed; written by
--                      the internal/security/audit Recorder. Severity is one
--                      of info|warn|crit so the sysop UI can colorize.
--
--   security_ip_bans — currently-active persistent IP bans (auto-promoted
--                      after N lockouts in the rolling window, or set
--                      manually by a sysop). Consulted on every auth attempt
--                      via an in-process cache that refreshes every 30s and
--                      push-invalidates over Redis pub/sub. expires_at is a
--                      wall-clock TTL so a cleanup goroutine can prune
--                      cheaply.

CREATE TABLE public.security_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_security_events PRIMARY KEY,
    at         timestamp with time zone NOT NULL DEFAULT now(),
    event_type text NOT NULL,
    severity   text NOT NULL,
    handle     text NULL,
    -- text rather than inet so it can hold IPv6 /64-collapsed CIDR keys
    -- ("2001:db8:1:2::/64") that netlimit emits.
    ip_addr    text NULL,
    details    jsonb NULL
);

CREATE INDEX ix_security_events_at      ON public.security_events (at DESC);
CREATE INDEX ix_security_events_ip_at   ON public.security_events (ip_addr, at DESC) WHERE ip_addr IS NOT NULL;
CREATE INDEX ix_security_events_type_at ON public.security_events (event_type, at DESC);

-- ip_addr is text rather than inet so it can hold the IPv6 /64-collapsed
-- form ("2001:db8:1:2::/64") that netlimit.CollapseIP returns. The lookup
-- side always normalizes to that same string form before comparing, so we
-- don't need inet's CIDR semantics here.
CREATE TABLE public.security_ip_bans (
    ip_addr    text NOT NULL CONSTRAINT pk_security_ip_bans PRIMARY KEY,
    banned_at  timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    reason     text NOT NULL,
    created_by text NOT NULL
);

CREATE INDEX ix_security_ip_bans_expires ON public.security_ip_bans (expires_at);
